### ISSUE TITLE
minLetterCount issue

### ISSUE THREAD

**Issue by vasilich-tregub** [alkozko/NHyphenator#2]
For minLetterCount=2 the last syllable always has 3 or more letters, even when it has 4 letters and can be hyphenated further to two two-letter syllables.

For example,

            var text = "обработано";
            Hyphenator hypenator = new Hyphenator(HyphenatePatternsLanguage.Russian, "-", 2, 2);
            var result = hypenator.HyphenateText(text);

gives result = "об-ра-бо-тано", although with Russian hyphenation rules "об-ра-бо-та-но" is valid and corresponds to the parameters of a Hyphenator constructor in the example given.

I propose to correct the code for a CorrectMask method in this way:

		private void CorrectMask(int[] hyphenationMask)
		{
			if (hyphenationMask.Length > minLetterCount)
			{
				Array.Clear(hyphenationMask, 0, minLetterCount);
				if (minLetterCount>2)
                    Array.Clear(hyphenationMask, hyphenationMask.Length - minLetterCount, minLetterCount);
			}
			else
				Array.Clear(hyphenationMask, 0, hyphenationMask.Length);
		}

with this correction, variable "result" in the example above becomes computed to "об-ра-бо-та-но".

**Comment by alkozko** [comment]
Hello! Sorry for delay.
I fixed this problem
