### ISSUE TITLE
Potential bug in `Compare(Pattern x, Pattern y)`

### ISSUE THREAD

**Issue by DumboJetEngine** [alkozko/NHyphenator#4]
This method never returns zero (even if the strings are equal) :

```
		public static int Compare(Pattern x, Pattern y)
		{
			bool first = x.str.Length < y.str.Length;
			int minSize = first ? x.str.Length : y.str.Length;
			for (var i = 0; i < minSize; ++i)
			{
				if (x.str[i] < y.str[i])
					return -1;
				if (x.str[i] > y.str[i])
					return 1;
			}
			return first ? -1 : 1;
		}
```
I see the calling code uses comparisons like this:

```
if (Pattern.Compare(patternFromWord, patterns[patternIndex]) >= 0){}
```

...so, could this be a bug?
(Note: the hyphenation does not work in some tests I do with greek text and I am trying to figure out what is wrong...)

**Comment by alkozko** [comment]
Unfortunately, I already forgot details about algorithm implementation.
This Compare function seems like with a bug. 
Can you provide example with incorrect greek hyphenation?
