### ISSUE TITLE
German is not hyphenated

### ISSUE THREAD

**Issue by LokiMidgard** [alkozko/NHyphenator#8]
I currently try to use this library to hyphenate german text. Unfortunalty I don't get it to work. I use the [pattern file](https://github.com/hyphenation/tex-hyphen/blob/76e373b4e486aa360563ad1c125f4db982d09e9f/hyph-utf8/tex/generic/hyph-utf8/patterns/txt/hyph-de-1996.pat.txt) as described in the readme. 

Loading the English (US) pattern the same way, does work. So I don't think it is a problem with the loading of the pattern file.

The word `Universitätsstadt`  should be hypeneted like this `Uni-ver-si-täts-stadt` . But the algorithm does not hyphenate it at all. It also does not hyphenate sentences.

Honestly I'm not yet understanding how the patterns work, so I can't say where it went wrong in the pattern match method.

**Comment by LokiMidgard** [comment]
There is a pattern `1si` in line 19291 in that file that should match. But somehow it does not work. When I remove all other patterns it will work (for this pattern).

**Comment by LokiMidgard** [comment]
Ok, I think I found the problem. The algorithm in `GenerateLevelsForWord` assumes an order list of patterns. However, The German pattern file, does not seems to be ordered that way.

I added an sort in the `CreatePatterns` method and it worked.

```c#
        private void CreatePatterns(string patternsString, string exeptionsString)
        {
            if (string.IsNullOrWhiteSpace(patternsString))
                throw new ArgumentException("Patterns must countain at least one pattern");

            var sep = new[] { ' ', '\n', '\r' };
            _patterns = patternsString.Split(sep, StringSplitOptions.RemoveEmptyEntries).Select(CreatePattern).ToList();
            _patterns.Sort();

            _exceptions = exeptionsString.Split(sep, StringSplitOptions.RemoveEmptyEntries).ToDictionary(x => x.Replace("-", ""), CreateHyphenateMaskFromExceptionString);
        }
```

**Comment by joaobsneto** [comment]
I had the same issue with portuguese, thanks for that!

**Comment by heulendoch** [comment]
> 
> 
> Ok, I think I found the problem. The algorithm in `GenerateLevelsForWord` assumes an order list of patterns. However, The German pattern file, does not seems to be ordered that way.
> 
> I added an sort in the `CreatePatterns` method and it worked.
> 
> ```cs
>         private void CreatePatterns(string patternsString, string exeptionsString)
>         {
>             if (string.IsNullOrWhiteSpace(patternsString))
>                 throw new ArgumentException("Patterns must countain at least one pattern");
> 
>             var sep = new[] { ' ', '\n', '\r' };
>             _patterns = patternsString.Split(sep, StringSplitOptions.RemoveEmptyEntries).Select(CreatePattern).ToList();
>             _patterns.Sort();
> 
>             _exceptions = exeptionsString.Split(sep, StringSplitOptions.RemoveEmptyEntries).ToDictionary(x => x.Replace("-", ""), CreateHyphenateMaskFromExceptionString);
>         }
> ```

If you sort the english pattern like this as well, you get some wrong english results.
The way like the sort() is sorting is not like the algo. is expecting order.

For e.g. try EnglishUs with and without Sort()
Without Sort() => aca-dem-ic
With Sort() => aca-d-e-m-ic

You need possible to implement an alternative sort algo. for german too, to get the best (better) results.

**Comment by joaobsneto** [comment]
I added sort in the portuguese pattern and I got good results. Maybe we should sort and store back in the file to not redo this step everytime.

**Comment by alkozko** [comment]
I've added optional param for sorting patterns, see https://github.com/alkozko/NHyphenator/blob/master/NHyphenator.Tests/HypenatorTests.cs#L126
